### PR TITLE
Add the projector options to the Symfony console command options

### PR DESCRIPTION
**Pull request by coudenysj**

### CODE REVIEW

**Comment by coudenysj** [comment]
https://github.com/prooph/pdo-event-store/issues/200

**Comment by ambroisemaupate** [comment]
Hi, @coudenysj 

Is this pull request still applicable ? We have the same issue with many projectors (8) running on the same docker stack and MySQL struggle to run them all. Especially when I want to reset read-model projections.

BTW, you did not pass your `$options` to `createReadModelProjection` method too: 
```php
$this->projector = $this->projectionManager->createReadModelProjection($this->projectionName, $this->readModel, $options);
```

**Comment by coudenysj** [comment]
@ambroisemaupate I think it is still applicable. I think we use a "userland" solution in out project, but your changes seem ok.

**Comment by codeliner** [comment]
Duplicate of https://github.com/prooph/event-store-symfony-bundle/pull/67

**Comment by unixslayer** [comment]
Projections options were released with 0.9.0 (#69)

**Pull request closed without merging**
