### PR TITLE
Created FQCN alias for the message factory service

### PR DESCRIPTION
**Pull request by gquemener**

### CODE REVIEW

**Comment by UFOMelkor** [comment]
> In addition, services not meant to be used by the application directly, should be defined as private. For public services, aliases should be created from the interface/class to the service id. 
*[Best Practices for Reusable Bundles](https://symfony.com/doc/current/bundles/best_practices.html#services)*

As I would read the Best Practices, services meant to be used by the user should be public. I'm not sure whether this is really necessar yfor the message_factory. Your thoughts on this?

**Comment by gquemener** [comment]
IMO, services should not be accessed at runtime (through `$container->get(...)`), so we could mark them all as private (as well as the aliases).

Like this we would not pollute the container if these services are injected nowhere.

Does it make sense :thinking: ?

**Comment by UFOMelkor** [comment]
Enough for me ;-)

**Comment by gquemener** [comment]
Ah ah, great :+1: 

Don't forget to tag a new release then, please :)

**Comment by UFOMelkor** [comment]
Will do after #43

**Pull request merged**
