### PR TITLE
WIP: Add Pdo Configuration segment

### PR DESCRIPTION
**Pull request by mablae**

### CODE REVIEW

**Comment by mablae** [comment]
@lunetics Here the part for PDO config you requested. How to advance from here?

**Comment by lunetics** [comment]
It would also be a good idea imho to allow existing connections or?

**Comment by mablae** [comment]
@lunetics Sure, could you share an example how you set one up? And how to manage it in config?  Thanks.

**Comment by vilnitsky** [comment]
for the existing symfony pdo connection I just added this service:
```
  doctrine.pdo.connection:
      class: PDO
      factory: ['@database_connection', getWrappedConnection]

```
works fine for me.

**Comment by codeliner** [comment]
I've merged the event store factory into master. This PR needs to be rebased and then we can think about further improvements. ping @mablae

**Comment by codeliner** [comment]
I tried @vilnitsky 's approach and it works like a charm. Thx man!

Reusing the doctrine connection is my favorite way here. In theory you don't need the doctrine bundle when working with prooph event store + a read models stored in NoSql databases, but if you go this route creating your own PDO connection should be an easy task.

So I'd say we don't need to spent more time here or at least wait until someone asks about it.

**Comment by mablae** [comment]
@codeliner @lunetics suggested the same. My argument was, that there would be two connection be made to the database, when the app has already a Doctrine connection layer. 

> So I'd say we don't need to spent more time here or at least wait until someone asks about it.

Okay

**Pull request closed without merging**
