### PR TITLE
Use --limit option in event-store:projection:names command

### PR DESCRIPTION
**Pull request by Miljar**
See bug report #51

### CODE REVIEW

**Comment by Miljar** [comment]
So what do we do with the failing 7.2 version? Create another PR with just the PHPCS fixes and then rebase this PR once it's merged?

**Comment by UFOMelkor** [comment]
PR looks great :+1: 

If you have some time to fix the CS as well, doing this and rebasing would be optimal.

**Comment by Miljar** [comment]
This PR is now rebased. You can merge it if you like. I'll be on holiday for the next 2 weeks, so any feedback you might have will be for when I've returned

**Comment by UFOMelkor** [comment]
Thank you very much!

**Pull request merged**
