### PR TITLE
Add EventStoreTransactionMiddleware to be used with symfony/messenger

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by kochen** [comment]
Nice work @Lctrs!
Could you add a small section/remark in the readme (or docs) on how to use it?

**Comment by Lctrs** [comment]
@kochen I can't find where the docs are for the bundle. And the readme doesn't seems to be for thing like this...

**Comment by Lctrs** [comment]
Ping @kochen. May you tell me where to put the doc please ?

**Comment by codeliner** [comment]
I just merged a long pending documentation PR. It was still WIP, but at least we have some docs in place now ;)

@Lctrs You could add an example here: https://github.com/prooph/event-store-symfony-bundle/blob/master/doc/configuration_reference.md

**Comment by Lctrs** [comment]
@codeliner Here it is. Waiting for your feedback :)

**Comment by codeliner** [comment]
cool, good job @Lctrs :+1:

**Pull request merged**
