### PR TITLE
projection options

### PR DESCRIPTION
**Pull request by unixslayer**
@codeliner @prolic 
- I was not able to pass projection options when defining projections so it couldn't be used when running projection with console command

### CODE REVIEW

**Comment by unixslayer** [comment]
resolves #49

**Comment by prolic** [comment]
can you add something to the docs on how to use it?

**Comment by unixslayer** [comment]
@prolic done. I've also supplement documentation with projection management. I somehow missed #67 and #59 ;)

**Comment by prolic** [comment]
awesome @unixslayer , thank you

**Pull request merged**
